version: '3.8'
services:
 db:
   container_name: postgres_container
   image: postgres
   restart: always
   environment:
     POSTGRES_DB: $POSTGRES_DB
     POSTGRES_USER: $DB_USER
     POSTGRES_PASSWORD: $DB_PASSWORD
     PGDATA: /var/lib/postgresql/data
   ports:
     - "54320:5432"
   volumes:
     - db-data:/var/lib/postgresql/data

 pgadmin:
   container_name: pgadmin4_container
   image: dpage/pgadmin4:latest
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: $PG_ADMIN_USER
     PGADMIN_DEFAULT_PASSWORD: $PG_ADMIN_PASSWORD
     PGADMIN_LISTEN_PORT: 80
   ports:
     - "8080:80"
   volumes:
     - pgadmin-data:/var/lib/pgadmin
volumes:
 db-data:
 pgadmin-data: